// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfE5pBscVNAorRPgw3UvnunpWpFDsv5M',
    appId: '1:697263691901:web:658c0fb2f2c9cd6935f914',
    messagingSenderId: '697263691901',
    projectId: 'khobraservices',
    authDomain: 'khobraservices.firebaseapp.com',
    storageBucket: 'khobraservices.firebasestorage.app',
    measurementId: 'G-7YGY7LQL79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWpOoHuA81Z80P-57MuDfO3M7aJ5_h6g',
    appId: '1:697263691901:android:f751dc8280ba650635f914',
    messagingSenderId: '697263691901',
    projectId: 'khobraservices',
    storageBucket: 'khobraservices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7eOx0jQT29MSL2kpQrma3Qp1N5P2FV4',
    appId: '1:697263691901:ios:ab744e947df0620235f914',
    messagingSenderId: '697263691901',
    projectId: 'khobraservices',
    storageBucket: 'khobraservices.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationNewproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh7eOx0jQT29MSL2kpQrma3Qp1N5P2FV4',
    appId: '1:697263691901:ios:ab744e947df0620235f914',
    messagingSenderId: '697263691901',
    projectId: 'khobraservices',
    storageBucket: 'khobraservices.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationNewproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkfE5pBscVNAorRPgw3UvnunpWpFDsv5M',
    appId: '1:697263691901:web:bc3561f0c300ba5635f914',
    messagingSenderId: '697263691901',
    projectId: 'khobraservices',
    authDomain: 'khobraservices.firebaseapp.com',
    storageBucket: 'khobraservices.firebasestorage.app',
    measurementId: 'G-Y1KJX3LPBT',
  );
}
